import React from 'react'

const PageB = () => (
  <div className="content">
    <p>pageBBB</p>
    <p>　　George R. R. Martin’s A Song of Ice and Fire series has become, in many ways, the gold standard for modern epic fantasy. Martin — dubbed the “American Tolkien” by Time magazine — has created a world that is as rich and vital as any piece of historical fiction, set in an age of knights and chivalry and filled with a plethora of fascinating, multidimensional characters that you love, hate to love, or love to hate as they struggle for control of a divided kingdom. It is this very vitality that has led it to be adapted as the HBO miniseries “Game of Thrones.”</p>
    <p>　　<strong>第一部: A GAME OF THRONE</strong></p>
    <p>　　Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister and supernatural forces are massing beyond the kingdom’s protective Wall. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the land they were born to. Sweeping from a land of brutal cold to a distant summertime kingdom of epicurean plenty, here is a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens.</p>
    <p>　　Here an enigmatic band of warriors bear swords of no human metal; a tribe of fierce wildlings carry men off into madness; a cruel young dragon prince barters his sister to win back his throne; and a determined woman undertakes the most treacherous of journeys. Amid plots and counterplots, tragedy and betrayal, victory and terror, the fate of the Starks, their allies, and their enemies hangs perilously in the balance, as each endeavors to win that deadliest of conflicts: the game of thrones.</p>
    <p>　　<strong>第二部: A CLASH OF KINGS</strong></p>
    <p>　　A comet the color of blood and flame cuts across the sky. Two great leaders — Lord Eddard Stark and Robert Baratheon — who hold sway over an age of enforced peace are dead, victims of royal treachery. Now, from the ancient citadel of Dragonstone to the forbidding shores of Winterfell, chaos reigns. Six factions struggle for control of a divided land and the Iron Throne of the Seven Kingdoms, preparing to stake their claims through tempest, turmoil, and war. It is a tale in which brother plots against brother and the dead rise to walk in the night. Here a princess masquerades as an orphan boy; a knight of the mind prepares a poison for a treacherous sorceress; and wild men descend from the Mountains of the Moon to ravage the countryside. Against a backdrop of incest and fratricide, alchemy and murder, victory may go to the men and women possessed of the coldest steel...and the coldest hearts. For when kings clash, the whole land trembles.</p>
    <p>　　<strong>第三部: A STORM OF SWORDS</strong></p>
    <p>　　Of the five contenders for power, one is dead, another in disfavor, and still the wars rage as violently as ever, as alliances are made and broken. Joffrey, of House Lannister, sits on the Iron Throne, the uneasy ruler of the land of the Seven Kingdoms. His most bitter rival, Lord Stannis, stands defeated and disgraced, the victim of the jealous sorceress who holds him in her evil thrall. But young Robb, of House Stark, still rules the North from the fortress of Riverrun. Robb plots against his despised Lannister enemies, even as they hold his sister hostage at King’s Landing, the seat of the Iron Throne. Meanwhile, making her way across a blood-drenched continent is the exiled queen, Daenerys, mistress of the only three dragons still left in the world. . . .</p>
    <p>　　But as opposing forces maneuver for the final titanic showdown, an army of barbaric wildlings arrives from the outermost line of civilization. In their vanguard is a horde of mythical Others — a supernatural army of the living dead whose animated corpses are unstoppable. As the future of the land hangs in the balance, no one will rest until the Seven Kingdoms have exploded in a veritable storm of swords. . .</p>
    <p>　　<strong>第四部： A FEAST FOR CROWS</strong></p>
    <p>　　It seems too good to be true. After centuries of bitter strife and fatal treachery, the seven powers dividing the land have decimated one another into an uneasy truce. Or so it appears. . . . With the death of the monstrous King Joffrey, Cersei is ruling as regent in King’s Landing. Robb Stark’s demise has broken the back of the Northern rebels, and his siblings are scattered throughout the kingdom like seeds on barren soil. Few legitimate claims to the once desperately sought Iron Throne still exist — or they are held in hands too weak or too distant to wield them effectively. The war, which raged out of control for so long, has burned itself out.</p>
    <p>　　But as in the aftermath of any climactic struggle, it is not long before the survivors, outlaws, renegades, and carrion eaters start to gather, picking over the bones of the dead and fighting for the spoils of the soon-to-be dead. Now in the Seven Kingdoms, as the human crows assemble over a banquet of ashes, daring new plots and dangerous new alliances are formed, while surprising faces — some familiar, others only just appearing — are seen emerging from an ominous twilight of past struggles and chaos to take up the challenges ahead.</p>
    <p>　　It is a time when the wise and the ambitious, the deceitful and the strong will acquire the skills, the power, and the magic to survive the stark and terrible times that lie before them. It is a time for nobles and commoners, soldiers and sorcerers, assassins and sages to come together and stake their fortunes . . . and their lives. For at a feast for crows, many are the guests — but only a few are the survivors.</p>
    <p>　<strong>　第五部： A DANCE WITH DRAGONS</strong></p>
    <p>　　In the aftermath of a colossal battle, the future of the Seven Kingdoms hangs in the balance — beset by newly emerging threats from every direction. In the east, Daenerys Targaryen, the last scion of House Targaryen, rules with her three dragons as queen of a city built on dust and death. But Daenerys has thousands of enemies, and many have set out to find her. As they gather, one young man embarks upon his own quest for the queen, with an entirely different goal in mind.</p>
    <p>　　Fleeing from Westeros with a price on his head, Tyrion Lannister, too, is making his way to Daenerys. But his newest allies in this quest are not the rag-tag band they seem, and at their heart lies one who could undo Daenerys’s claim to Westeros forever.</p>
    <p>　　Meanwhile, to the north lies the mammoth Wall of ice and stone — a structure only as strong as those guarding it. There, Jon Snow, 998th Lord Commander of the Night’s Watch, will face his greatest challenge. For he has powerful foes not only within the Watch but also beyond, in the land of the creatures of ice.</p>
    <p>　　From all corners, bitter conflicts reignite, intimate betrayals are perpetrated, and a grand cast of outlaws and priests, soldiers and skinchangers, nobles and slaves, will face seemingly insurmountable obstacles. Some will fail, others will grow in the strength of darkness. But in a time of rising restlessness, the tides of destiny and politics will lead inevitably to the greatest dance of all.</p>
    <p><strong>作者簡介</strong></p>
    <p><strong>當代歐美文壇最重要的奇幻小說大師──喬治．馬汀（George R. R. Martin）</strong></p>
    <p>　　一九四八年出生於美國紐澤西州的貝約恩市。二十七歲即以《萊安娜之歌》獲象徵科幻小說界最高成就的「雨果獎」，此後得獎連連，曾獲四次「雨果獎」、兩次「星雲獎」、一次「世界奇幻文學獎」及十一次「軌跡獎」。二○一一年更入選《時代雜誌》百大影響人物。</p>
    <p>　　喬治．馬汀是當今歐美最受推崇的奇幻小說作家之一，曾擔任「新陰陽魔界」和「美女與野獸」等電視影集編劇總監，他的早期作品多為科幻，尤以短篇見長，筆調瑰麗、感傷而富浪漫色彩。長篇作品則包括《光之逝》、《風港》、《熾熱之夢》、《末日狂歌》，以及預計共七部的奇幻小說「冰與火之歌」系列，第五部即將在二○一一年七月於美國出版。</p>
    <p>　　「冰與火之歌」系列是近年來史詩奇幻小說的一大突破，他以寬廣的格局，史家般的寫實筆觸，跌宕而驚奇不斷的情節，革命性地拓展了奇幻小說的視野，已連續多年蟬聯亞馬遜網路書店年度最佳奇幻小說。</p>
    <p>　　喬治．馬汀官方網站：<a>www.georgerrmartin.com/</a></p>
    <p>　　George R.R. Martin sold his first story in 1971 and has been writing professionally since then. He spent ten years in Hollywood as a writer-producer, working on The Twilight Zone, Beauty and the Beast, and various feature films and television pilots that were never made. In the mid ’90s he returned to prose, his first love, and began work on his epic fantasy series, A Song of Ice and Fire. He has been in the Seven Kingdoms ever since. Whenever he’s allowed to leave, he returns to Santa Fe, New Mexico, where he lives with the lovely Parris, a big white dog called Mischa, and two cats named Augustus and Caligula, who think they run the place.</p>
  </div>
)

export default PageB